# Train
epochs: 800
blr: 0.0001 # this is base_lr = 1e-4, lr = base_lr * batch_size / 256
warmup_lr: 0.000001 # 1e-6
min_lr: 0.
warmup_epochs: 40
batch_size: 5 # 136 # 256 <---------------------
hflip: 0.5

# Data
data_path: '/kaggle/input/multimae-v1' # Change me
data_paths:
  - 'datasets/multimae-v1'
  # - 'datasets/nyu-depth-v2'

# Wandb logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project: PretrainSMultiMAE
output_dir: './output/pretrain' # Change directory if needed
normalized_depth: True

depth_range: 256
depth_loss: "mse"
pretrained_weights: 'pretrained_weights/multimae-b_98_rgb-depth-semseg_1600e_multivit-afff3f8c.pth'
