# Train
epochs: 800
blr: 0.0001 # this is base_lr = 1e-5, lr = base_lr * batch_size / 256
warmup_lr: 0.00001 # 1e-5
min_lr: 0.
warmup_epochs: 5
batch_size: 128 # 136 # 256 <---------------------
save_ckpt_freq: 3

# Data
data_path: '/kaggle/input/multimae-v1' # Change me
data_paths:
  - '/kaggle/input/multimae-v1'
  - '/kaggle/input/nyu-depth-v2'

# Wandb logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project: PretrainSMultiMAE
output_dir: './output/pretrain' # Change directory if needed
normalized_depth: True

depth_range: 256
depth_loss: "mse"
pretrained_weights: '/kaggle/input/pretrainedweightsmultimae/multimae-b_98_rgb-depth-semseg_1600e_multivit-afff3f8c.pth'
gpus:
  - 0
  - 1
