# Train
epochs: 1000
blr: 1e-6 # this is base_lr = 1e-4, lr = base_lr * batch_size / 256
elr: 1e-8
lr_strategy_version: 2
is_wd_schedule: False
batch_size: 10 # 312
save_ckpt_freq: 3

# Data
data_path: 'v1'

# Wandb logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project: PretrainSMultiMAE
output_dir: './output/pretrain' # Change directory if needed
normalized_depth: True

depth_range: 256
depth_loss: "l1"
pretrained_weights: 'pretrained_weights/mae-b_dec512d8b_1600e_multivit-c477195b.pth'
pretrained_backbone: 'mae'
lr_scale: 1000
data_augmentation_version: 1
num_workers: 12
devices: [2]
check_val_every_n_epoch: 2
weight_decay: 0.8
clip_grad: 1.0
